version: '2'

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_USER: wordpress
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_PASSWORD: wordpress
    ports:
      - ${MYSQL_PORT}:3306
    networks:
      - backend

  wordpress:
    depends_on:
      - mysql
    image: conetix/wordpress-with-wp-cli
    restart: always
    environment:
      VIRTUAL_HOST: maps.local
      VIRTUAL_PORT: ${WORDPRESS_PORT}
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    ports:
      - ${WORDPRESS_PORT}:80
    volumes:
      - ./:/var/www/html/wp-content/plugins/nelio-maps
    networks:
      - backend
      - frontend

networks:
  backend:

  frontend:
    external:
      name: local-by-nelio
