#!/bin/bash

FILES=("$@")

PHPCBF_FILES=("${FILES[@]}")
if [ ${#FILES[@]} -eq 0 ]; then
	# shellcheck disable=SC2207
	PHPCBF_FILES=($(fd -t f -E scripts/ -E php-stubs/ "\.php$|\.html$"))
fi

gum spin --title="Formatting PHP…" -- ./vendor/bin/phpcbf --parallel=16 --standard=.phpcs.xml "${PHPCBF_FILES[@]}"
exit 0
