#!/bin/bash
# shellcheck disable=SC2207

FILES=("$@")
if [ ${#FILES[@]} -eq 0 ]; then
	FILES=($(fd -t f --ignore-file .eslintignore -E "*.d.ts" "\.[tj]sx?$"))
fi

# if ! "$(dirname "$0")"/wp-scripts lint-js "${FILES[@]}"; then
# 	exit 80
# fi

if ! "$(dirname "$0")"/generate-build-checksum | diff -q .last-valid-build - >/dev/null 2>&1; then
	if ! "$(dirname "$0")"/wp-scripts format-js "${FILES[@]}"; then
		exit 81
	fi

	if ! gum spin --title="Checking TypeScript types…" --show-error -- yarn run build; then
		exit 82
	fi
fi
